### ISSUE TITLE
IE 11 Error (Vue warn)

### ISSUE THREAD

**Issue by otherJeannie** [Yuliang-Lee/vue2-smooth-scroll#1]
i am getting an error in the console when loading in IE 11:

```
[Vue warn]: Error in directive smooth-scroll inserted hook: "TypeError: Object doesn't support property or method 'assign'"
found in
---> <NavBar> at src\components\NavBar.vue
```

below this is the object Error. i do not get this error on Firefox or Chrome. i am using the meta tag `<meta http-equiv="X-UA-Compatible" content="IE=edge" />` and a proper doctype. i do not have any other console errors. 

let me know if you need more details - i am not sure how to create a jsfiddle for Vue using a package.

Edit: is native smooth scrolling supported by feature detection?

**Comment by Yuliang-Lee** [comment]
Thank for feedback.

fix in https://github.com/Yuliang-Lee/vue2-smooth-scroll/commit/9907a30f656503bc93ccd125ae3b241595384be6

If still has compatibility issues plz reopen this.
