### ISSUE TITLE
Setting active class of menu item

### ISSUE THREAD

**Issue by marcodeluca** [Yuliang-Lee/vue2-smooth-scroll#14]
One of the nicer smooth scrolls for vuejs - a nice feature would be to set and detect the active class for the menu/link. An example: https://ibufu.github.io/vue2-scrollspy/

**Comment by Yuliang-Lee** [comment]
These are two tools for different functions. This tool is mainly used for things like the back to top button. https://github.com/Yuliang-Lee/vue-scrollspy
