### ISSUE TITLE
Error when using v-smooth-scroll on other component instead of <a> element

### ISSUE THREAD

**Issue by makkus183** [Yuliang-Lee/vue2-smooth-scroll#15]
I am trying to use smooth scroll on an other element than `<a>`, instead i want to use
`<b-nav-item href="#">Link</b-nav-item>` from [bootstrap-vue Navbar component](https://bootstrap-vue.js.org/docs/components/navbar/#navbar) :  

```
<b-nav-item
    href="#content-1"
    v-smooth-scroll
    class="text-uppercase"
>
```
But i get the following error in Browser Console:  

`vue-smooth-scroll.min.js?5a58:formatted:110 Uncaught TypeError: Cannot read property 'substring' of undefined at HTMLLIElement.eval (vue-smooth-scroll.min.js?5a58:formatted:110)`

If I am using smooth scroll on a regular `<a>`element like this:

```
<a
    href="#content-1"
    v-smooth-scroll
 >Test</a>
```

it´s working fine.

**Comment by muhammedjenos** [comment]
I have encountered this issue today. I have an anchor link defined as component and attaching the directive on the component just make the page jump to the ID and not scrolling smooth. Is there a way to make this work?

**Comment by Yuliang-Lee** [comment]
> I have encountered this issue today. I have an anchor link defined as component and attaching the directive on the component just make the page jump to the ID and not scrolling smooth. Is there a way to make this work?

please provide a reproduction link

**Comment by smitpatelx** [comment]
@Yuliang-Lee I encountered same issue while using nuxt js in universal mode. I am using it like this:
` <nuxt-link v-smooth-scroll>`.

How to reproduce:
Install nuxt js in **universal** mode and use `nuxt-link`

**Comment by cata-libuy** [comment]
Same problem with nuxt

**Comment by smitpatelx** [comment]
@cata-libuy I solved this problem by uninstalling this package and do this instead.

```
html, body{
    scroll-behavior: smooth;
}
```
To check supported browsers : [https://caniuse.com/#feat=css-scroll-behavior](https://caniuse.com/#feat=css-scroll-behavior)
