### ISSUE TITLE
how to use with <a href="/#foo">

### ISSUE THREAD

**Issue by wanderingcrow** [Yuliang-Lee/vue2-smooth-scroll#18]
Sorry, this is probably my limited understanding of javascript. I have a site that is mostly just a single page and my header nav links to various anchors on the home page. However, I have a couple of exceptions: blog, for instance. So, all of my links are preceded by a slash to bring users back to the home page anchors. 

In std html, this works fine: 
`<a href="/#foo">Foo</a>`

With `v-smooth-scroll`, `#foo` works, `/#foo` does not. Obviously, I need the `/` if I'm coming from any other page than index. 

Any ideas what I'm doing wrong? 

Actual code (pug): 
`a(href="/#contact" v-smooth-scroll) contact`

**Comment by Yuliang-Lee** [comment]
I'm a little confused about your title and description..
the title is `href="#/foo"` but actual code is `href="/#contact"`.

I assume you are using vue-router's hash mode, the target element is `<div id="yourId"></div>` so anchor element should be `<a href="#yourId" v-smooth-scroll="{updateHistory: false}"></a>`

**Comment by wanderingcrow** [comment]
Sorry, I had a typo in my title. 

I'm actually using with Gridsome. It works beautifully without the `/`, but for some reason the slash messes it up. I didn't know about the hash mode, but Googling it led me to this: https://github.com/gridsome/gridsome/issues/356, which leads me to wonder if it's something with the way Gridsome is working. 

I appreciate any and all help, and it would be lovely to get this to work. But it seems like it has nothing to do with your repo. Sorry to bug you, I'll close. Normal CSS smooth scroll works for most browsers: https://www.w3schools.com/howto/howto_css_smooth_scroll.asp

**Comment by a-kriya** [comment]
@wanderingcrow Try checking for a route hash in the `mounted` hook (or perhaps `beforeRouteEnter` if the browser has already moved to the `#element` by the time `mounted` gets triggered) on your `/` page, and [call `smoothScroll` method programmatically](https://github.com/Yuliang-Lee/vue2-smooth-scroll/pull/12) to scroll to that element.

This may help: https://stackoverflow.com/a/29823913

**Comment by atiar-cse** [comment]
The codes are working but the problem is, when I have the href like `<a href="/#anchor">Anchor</a>`, it does not seem to work with my codes. If I have the same without the forward slash, it works like `<a href="#anchor">Anchor</a>`. 
When visit new route (/contact-us) - it loaded as base_url/contact-us#anchor and never works.

I am using vue-router.

Any help will be appreciated.
