### ISSUE TITLE
Passing arguments does nothing

### ISSUE THREAD

**Issue by pieter-janDB** [Yuliang-Lee/vue2-smooth-scroll#21]
Hi,

I tried using the config but nothing changes with passing any config.

I tried this:
```
<a v-smooth-scroll="{ duration: 3000, offset: -50, container: '#container', updateHistory: false }" href="#id"></a>
```
note the 3000 duration, but it takes equally long as if I wasn't passing anything. I also tried passing a data variable with this object. I tried different durations, changing offset, giving the container the id "container" but nothing seem to work. Also only passing one attribute does not do anything.

This is the way I import it in my vue component:
```
import vueSmoothScroll from 'vue2-smooth-scroll'
import Vue from 'vue'
Vue.use(vueSmoothScroll);
```

**Comment by Yuliang-Lee** [comment]
could you use [codepen](https://codepen.io/) reproduces your problem?

**Comment by pieter-janDB** [comment]
I use webpack to compile, it seems to only be a problem while developing, once I make a build it works.

**Comment by a-kriya** [comment]
@pieter-janDB Does your dev environment have hot-reloading? Also try clearing browser cache.

Can you share a stripped down version of your code that demonstrates the issue?
