### ISSUE TITLE
can you programmatically invoke the smooth scroll after an `e.preventDefault()?`

### ISSUE THREAD

**Issue by heaversm** [Yuliang-Lee/vue2-smooth-scroll#22]
I want to perform some other functionality in javascript in addition to scrolling to the anchor, does this library support that?

**Comment by Yuliang-Lee** [comment]
next version will support programmatic usage. https://github.com/Yuliang-Lee/vue2-smooth-scroll/pull/12

**Comment by Yuliang-Lee** [comment]
please update to v1.4.0. https://github.com/Yuliang-Lee/vue2-smooth-scroll/pull/12
