### ISSUE TITLE
Broken SSR in v1.4.x

### ISSUE THREAD

**Issue by a-kriya** [Yuliang-Lee/vue2-smooth-scroll#26]
`install` method of the plugin is called during SSR, and with v1.4.0 it contains the following declaration that results in a `window not defined` error:

```js
const defaultValue = {
  duration: 500,
  offset: 0,
  container: window,
  updateHistory: true,
};
```

![image](https://user-images.githubusercontent.com/26761352/84840709-fbbaec80-b05d-11ea-941b-02cc1443d888.png)

@Yuliang-Lee @jwhitmarsh Sorry for missing that in the review! I'll try to come up with a good way to fix and create a PR, but I'm open to suggestions.

**Comment by jwhitmarsh** [comment]
How about something like https://github.com/jwhitmarsh/vue2-smooth-scroll/commit/e709313c08be28612eb3232fb547579d385fc1d0

**Comment by Yuliang-Lee** [comment]
fixed in https://github.com/Yuliang-Lee/vue2-smooth-scroll/issues/26
