### ISSUE TITLE
Prevent hash in URL

### ISSUE THREAD

**Issue by bokub** [Yuliang-Lee/vue2-smooth-scroll#3]
Hi,

Your component works perfectly, but I'm annoyed by the hash in the URL, I just want the smooth scroll to happen.

![image](https://user-images.githubusercontent.com/17952318/50541481-364d7280-0ba7-11e9-9ba9-64f26abaf4c5.png)

Would you consider an option to scroll without adding the hash? 

I guess the the only thing to do would be to add the following line when that option is activated:

```js
history.pushState('', document.title, window.location.pathname);
```

Thanks a lot 👍

**Comment by bokub** [comment]
I have found a temporary and dirty way to hide the hash as soon as your component adds it.

```js
export default {
    mounted() {
        window.addEventListener('popstate', () => {
            history.pushState('', document.title, window.location.pathname);
        });
    },
    methods: {
        onClick() {
            this.$nextTick(() => {
                history.pushState('', document.title, window.location.pathname);
            });
        }
    }
};
```

**Comment by Yuliang-Lee** [comment]
Sorry to reply so late, *hash* will not be removed, because it needs to be used when going backwards. You can copy the source code to the project and modify it yourself.

**Comment by bokub** [comment]
Well, I don't want my users to go backwards actually...

But that's your call, thanks anyways :+1:
