### ISSUE TITLE
Running the app on IE11 causes error: Expected Identifier

### ISSUE THREAD

**Issue by djurdjen** [Yuliang-Lee/vue2-smooth-scroll#31]
First of all, thanks for making this awesome package!

I found a bug when updating to version 1.5.0 causes the following console error in IE11: _Expected Identifier_ in the `chunk-vendors.js`
Not much else is being shown

**Comment by Yuliang-Lee** [comment]
Would you mind providing the file chunk-vendors.js

**Comment by xfdrer** [comment]
IE breaks on this line

`
function _smoothScroll({
`

**Comment by dneeleman** [comment]
I can concur, including the plugin directly fails for IE11. Copying the src of the plugin 1:1 into our plugin file will resolve the issues automatically on build time with Babel. I have found no time yet to investigate as of why and what is causing the issue.

Using Nuxt 2.14.7. Running plugin client side only.

**Comment by Jaloko** [comment]
Having the same issue. I've rolled back to 1.4.2 as it seems to work fine.

**Comment by Yuliang-Lee** [comment]
I think this problem may be cause by https://github.com/Yuliang-Lee/vue2-smooth-scroll/issues/44 as well, try upgrade to v1.5.1.
I apologise with my careless
