### ISSUE TITLE
Running in Vue 3.0

### ISSUE THREAD

**Issue by larsvdd** [Yuliang-Lee/vue2-smooth-scroll#35]
Hi there,

Anyone got this working in Vue 3.0? 
I'm not sure how to do the importing etc. I tried doing it the same as in Vue 2.0 (like in the example), but that doesn't work.

**Comment by Yuliang-Lee** [comment]
I'm working on support Vue 3

**Comment by Yuliang-Lee** [comment]
According to this package name may be confused by people use vue3.x, I made a new package https://github.com/Yuliang-Lee/v-smooth-scroll . please use new package
