### ISSUE TITLE
How to use programmatically within a component?

### ISSUE THREAD

**Issue by iwasherefirst2** [Yuliang-Lee/vue2-smooth-scroll#36]
How can I use this in a component without registering it in Vue `Vue.use(VueSmoothScroll, {
  duration: 400,
  updateHistory: false,
})` 

?

**Comment by nemesisKO** [comment]
any answers?

**Comment by Yuliang-Lee** [comment]
It can't, it is a vue plugin
the reason why can't register to vue?

**Comment by Yuliang-Lee** [comment]
may be this [scroll-behavio](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) css property will help you
