### ISSUE TITLE
"scrolling behavior: smooth" breaks the library

### ISSUE THREAD

**Issue by Enc0re3gone** [Yuliang-Lee/vue2-smooth-scroll#42]
In my app, I'm scrolling through a container, and when I set the css property for it to "scroll behavior: smooth" - it breaks on the desktop computer. After clicking on the anchor, it thinks for a long time, and then teleports to about the anchor + - 10% of the height.

I think you should mention this in the description, I had to spend some time to understand why the library is not working correctly in my application

**Comment by Yuliang-Lee** [comment]
ok, thanks your advice
