### ISSUE TITLE
Wrong main file in package.json on npm

### ISSUE THREAD

**Issue by Kapcash** [Yuliang-Lee/vue2-smooth-scroll#44]
Hi!
On the last published version on npm (1.5.0), the `main` entry from package.json points to `src/index.js` instead of `dist/vue-smooth-scroll.min.js`. So it breaks on nodejs as it's not compiled to UMD.

I see on github it points to the right file so I guess it's a mistake when the version has been deployed? :)

(Check here: https://unpkg.com/vue2-smooth-scroll@1.5.0/package.json)

**Comment by Yuliang-Lee** [comment]
I'm sorry for this careless unacceptable mistake. It already fixed in v1.5.1
