### ISSUE TITLE
Request: need to add callback function

### ISSUE THREAD

**Issue by balalaXD** [Yuliang-Lee/vue2-smooth-scroll#6]
Case:

I have a sticky navbar and the height is different from mobile and desktop, so I have to change the offset from mobile and desktop to not cover the content. i want an function to be call returning an object.

**Comment by Yuliang-Lee** [comment]
You can set up different offset on different platforms. I don't understand what callback you want

**Comment by balalaXD** [comment]
**something like this more flexible:**

```html
<div id="container">
  <a href="#div-id" v-smooth-scroll="{ duration: 1000, offset: -50, container: '#container' }">Anchor</a>
  <!-- or if parameter is callback function then call it -->
  <a href="#div-id" v-smooth-scroll="getSmoothScrollObject">Anchor</a>
  <div id="div-id"></div>
</div>
```

script:
```javascript
const getSmoothScrollObject = () => {
    const height = this.$refs.navbar.clientHeight
    return {
       duration: 1000,
       offset: -height,
       container: '#container'
    }
}
```

**Comment by Yuliang-Lee** [comment]
You can use [computed property](https://vuejs.org/v2/guide/computed.html#Computed-Properties) or just use a variable. I can't find any benefit or different that use function.

**Comment by balalaXD** [comment]
emmm, yeah, that make sense

**Comment by balalaXD** [comment]
Because the [computed property](https://vuejs.org/v2/guide/computed.html#Computed-Properties) can't access `$refs` until the component first render is done, and `$refs` is not reactive, it's explicitly not recommended to use `$refs` inside computed properties.

But workaround is **NOT** work also
```javascript
Vue.component('navbar', {
  template:`...`
  data(){
    return {
      isMounted: false
    }
  },
  computed:{
    navbarHeight(){
      if(!this.isMounted)
        return;
      let height = this.$refs.navbar2.clientHeight
      console.log(height)
      return height
    }
  },
  mounted(){
    this.isMounted = true;
  }
})
```

so maybe add callback is worth tough.

**Comment by balalaXD** [comment]
http://jsfiddle.net/u3vj5sw6/2/
