### ISSUE TITLE
How to prevent href default behaviour?

### ISSUE THREAD

**Issue by NeoTianHow** [Yuliang-Lee/vue2-smooth-scroll#7]
In my component, I have the following code: 

` <a href="#test" class="mouse-icon" @click.prevent="preventDefault" v-smooth-scroll>`

I was able to scroll to the element, with an id of #test as shown in the following code

 `<div id="test"></div>`

However, I notice that the id "test" will be appended at the end of the URL. how do you stop that from happening? For example, 

http://localhost:8081/#/test

**Comment by Yuliang-Lee** [comment]
replicated https://github.com/Yuliang-Lee/vue2-smooth-scroll/issues/3
