### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by juanlatorre** [Yuliang-Lee/vue2-smooth-scroll#8]
When using with Gridsome works perfectly on develop, but when I use "gridsome build" it throws an error.

![image](https://user-images.githubusercontent.com/4494526/59956436-524b1600-945e-11e9-861a-e6b41bbcdc05.png)

**Comment by Yuliang-Lee** [comment]
may be this issue will help you https://github.com/gridsome/gridsome/issues/474

**Comment by juanlatorre** [comment]
Thank you very much !
